version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Zipping application for deployment"
      - zip -r ../app.zip . -x "*.git*"  # excludes .git files from the zip

artifacts:
  files:
    - '**/*'
